name: hp-tuning

on:
  pull_request_target:
    branches: main

permissions:
  contents: write
  pull-requests: write


jobs:
  hp_tune:
    if: startsWith(github.head_ref, 'hp_tune/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # ✅ Installer DVC
      - name: Setup DVC
        uses: iterative/setup-dvc@v2

      # ✅ Installer CML
      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DVC hyperparameter tuning
        run: dvc repro -f hp_tuning

      - name: Create Pull Request for training branch
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr create \
          --user-email hp-bot@cicd.ai \
          --user-name HPBot \
          --message "HP tuning" \
          --branch train/${{ github.sha }} \
          --target-branch main \
          rfc_best_params.json
